# 异常

## 什么是异常

- 实际工作中，遇到的情况不可能是非常完美的
- 软件程序在运行过程中，非常可能遇到问题：异常---Excepion
- 异常指程序运行中出现的不期而至的各种状况
- 异常发生在程序运行期间，它影响了正常的程序执行流程

## 简单分类

- 要理解Java异常处理是如何工作的，你需要掌握以下三种类型的异常：
- 检查性异常：最具代表的检查性异常是用户错误或问题引起的异常，这是程序无法预见的
- 运行时异常：运行时异常是可能被程序员避免的异常。与检查性异常相反，运行时异常可以在编译时被忽略
- 错误ERROR：错误不是异常，而是脱离程序员控制的问题。错误在代码中通常被忽略。

## 异常体系结构

- Java把异常当作对象来处理，并定义一个基类java.lang.Throwable作为所有异常的超类
- 在Java  API中已经定义了许多异常类，这些异常类分为两大类，错误ERROR和异常Exception.

![image-20201003101251787](C:\Users\ycc\AppData\Roaming\Typora\typora-user-images\image-20201003101251787.png)

### ERROR

- Error类对象由Java虚拟机生成并抛出，大多数错误与代码编写者所执行无关
- Java虚拟机运行错误(Virtual MachineError),当JVM不再有继续执行操作所需的内存资源时，将出现OutOfMemoryError.发生这种异常时，Java虚拟机

- 还有发生在虚拟机试图执行应用时，如类定义错误（NotClassDefFoundError）,链接错误（LinkageError）.这些错误是不可查的，因为它们在应用程序的控制和处理能力之外，而且绝大多数是程序运行时不允许出现的情况

### Exception

- 在Exeption分支中有一个重要的子类RuntimeException(运行时异常)
  - ArrayIndxOutOfBoundsException(数组下标越界)
    - NullPointerException(空指针异常)
    - ArithMeticExcption(算数异常)
    - MissingResourceException(丢失资源)
    - Class Not Found Exception(找不到类)等异常，这些异常是不检查异常，程序中可以选择捕获处理，也可以不处理
- 这些异常一般是由程序逻辑错误引起的，程序应该从逻辑角度尽可能避免这类异常的发生；
- Error和Exception的区别：Error通常是灾难性的致命的错误，是程序无法控制和处理的，当出现这些异常时，java虚拟机（JVM）一般会选择终止线程；Exception通常情况下是可以被程序处理的，并且在程序中应该尽可能的去处理这些异常

## Java异常处理机制

- 抛出异常

- 捕获异常

  ```java
  public class dome01 {
      public static void main(String[] args) {
          int a = 1;
          int b = 0;
          try {//监控区
              System.out.println(a/b);
          }catch (Exception e){//catch(想要捕获的异常类型)捕获异常
              System.out.println("被除数不能为零");
          }finally {//处理善后工作
              System.out.println("succes full");
          }
      }
  }
  ```

## 处理异常

- try

- catch捕获

- fianlly善后

- throw主动抛出

  ```java
  public class dome01 {
      public static void main(String[] args) {
          new dome01().test(1,0);
      }
      public void test(int a, int b){
          if(b==0){
              throw new ArithmeticException();
          }
          System.out.println(a/b);
      }
  }
  ```

- throws抛出到上一级，继续执行之后的

  ```java
  public class dome01 {
      public static void main(String[] args) {
          try {
              new dome01().test(1,0);
          } catch (Exception e) {
              System.out.println("错误");
          }
      }
      public void test(int a, int b) throws Exception {
          if(b==0){
              throw new ArithmeticException();
          }
          System.out.println(a/b);
      }
  }
  ```

## 自定义异常

- 使用Java内置的异常类可以描述在编程时出现的大部分异常情况。除此之外，用户还可以自定义异常，用户自定义异常类，只需要继承Exception类即可

- 在程序中使用自定义异常类，大体可分为以下几个步骤：
  1. 创建自定义异常类
  2. 在方法中通过throw关键字抛出异常
  3. 如果在当前抛出异常的方法中处理异常，可以使用try-catch语句捕获并处理；否则在方法的声明处通过throws关键字指名要抛出给方法调用者的异常，继续进行下一步操作
  4. 在出现异常方法的调用者捕获并处理异常
  
  ```java
  public class test {
      static  void test(int a ) {
          System.out.println("传递的参数是:"+a);
          if (a>10){
              try {
                  throw new dome01(a);
              } catch (com.trycatch.dome01 dome01) {
                  System.out.println(dome01);
              }
          }
          System.out.println("OK");
      }
      public static void main(String[] args) {
          test.test(11);
      }
  }
  ```
  
  ```java
  public class dome01 extends Exception {
      private int detail;
      public dome01(int a){
          detail = a;
      }
      //异常的打印信息
      @Override
      public String toString() {
          return "dome01{" +
                  "detail=" + detail +
                  '}';
      }
  }
  ```

## 总结

- 处理运行异常时，采用逻辑去合理规避同时辅助try-catch处理
- 在多重catch块后面，可以加一个catch(Exception)来处理可能会被遗漏的异常
- 对于不确定的代码，也可以加上try-catch,处理潜在的异常
- 尽量去处理异常，切忌只是简单调用printStackTrace()去打印输出
- 具体如何处理异常，要根据不同的业务需求和异常类型去决定
- 尽量添加finally语句块去释放占用的资源